name: ci
on:
  push:
    branches: 
      - 0.10.x
concurrency: 
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  x86_64-linux-debug:
    runs-on: [self-hosted, Linux, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: sh ci/x86_64-linux-debug.sh
  x86_64-linux-release:
    runs-on: [self-hosted, Linux, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: sh ci/x86_64-linux-release.sh
  aarch64-linux-debug:
    runs-on: [self-hosted, Linux, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: sh ci/aarch64-linux-debug.sh
  aarch64-linux-release:
    runs-on: [self-hosted, Linux, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: sh ci/aarch64-linux-release.sh
  x86_64-macos:
    runs-on: "macos-11"
    env:
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ci/x86_64-macos.sh
