name: ci
on:
  pull_request:
  push:
    branches: 
      - master
jobs:
  x86_64-linux-debug:
    outputs:
      version: ${{ steps.version.outputs.version }}
    runs-on: [self-hosted, Linux, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: sh ./ci/linux/build-x86_64-debug.sh
      # The following step is required by the build-tarballs job.
      # If this job is being deleted / commented out, make sure
      # to have another job provide this information.
      - name: Get Version
        id: version
        run: echo "version=$(stage3-debug/bin/zig version)" >> $GITHUB_OUTPUT
  x86_64-linux-release:
    runs-on: [self-hosted, Linux, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: sh ./ci/linux/build-x86_64-release.sh
  x86_64-macos:
    runs-on: "macos-11"
    env: 
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ./ci/macos/build-x86_64.sh
  x86_64-windows:
    runs-on: windows-latest
    env: 
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ./ci/windows/build.ps1
  aarch64-linux:
    runs-on: [self-hosted, Linux, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: sh ./ci/linux/build-aarch64.sh
  aarch64-macos:
    runs-on: [self-hosted, macOS, aarch64]
    env: 
      ARCH: "aarch64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ./ci/macos/build-aarch64.sh
